---
# app
prefix      : /srv
app_home    : "{{ prefix }}/sentry"
app_env     : "{{ app_home }}/env"
app_public  : "{{ app_home }}/public"
app_assets  : "{{ app_public }}/static"
app_log     : "/var/log/nginx/sentry"
tmp_path    : "{{ prefix }}/tmp"
app_user    : www-data
app_group   : www-data

# pgsql
dbname     : sentry
dbuser     : sentry_user
dbpassword : demo
