---
# Install Nginx

- name: nginx-apt
  apt: pkg={{ item }} state=installed
  with_items:
    - nginx
  tags: nginx
  sudo: yes

# Remove Default Site
- name: nginx-rm-default
  file: path=/etc/nginx/sites-enabled/default state=absent
  sudo: yes