---
# This is the top-level playbook that defines our entire infrastructure.

- hosts: all
  gather_facts: False
  sudo: no
  vars:
    #installer_local : 
  roles:
    - common
    - nginx
    - pgsql
    - sentry

