---
# Dependencies
- name: sentry-deps_apt
  apt: pkg={{ item }} state=installed
  with_items:
    - python-dev
    - python-virtualenv
    - python-pip
  sudo: yes

- name: sentry-preinst_installer_dirs
  file: path={{ prefix }} state=directory owner={{ app_user }} group={{ app_group }}
  sudo: yes

- name: sentry-install
  pip: name={{ item }} virtualenv={{ app_env }}
  sudo: no
  with_items:
   - psycopg2
   - sentry
  sudo_user: "{{ app_user }}"
  sudo: yes

# Config 
- name: sentry-conf_app_dirs
  file: path={{ item }} state=directory owner={{ app_user }} group={{ app_group }} recurse=yes
  with_items:
    - "{{ app_assets }}"
    - "{{ app_log }}"
  sudo: yes

- name: sentry-conf_config_file
  template: src=sentry.conf.py dest={{ app_home }}/sentry.conf.py owner={{ app_user }} group={{ app_group }}
  sudo: yes

# Post-Inst
# - name: sentry-postinst-data-upload
#   template: src=initial_data_admin.json dest={{ app_home }}/initial_data_admin.json owner=www-data group=www-data

- name: sentry-postinst-upgrade
  shell: "{{ app_env }}/bin/sentry --config={{ app_home }}/sentry.conf.py upgrade"
  sudo_user: "{{ app_user }}"
  sudo: yes
