---

# Start Supervisor
- name: supervisor_start
  shell: service supervisor start

# Configure supervisor
- name: supervisor_add_app
  template: src=supervisor.conf.j2 dest=/etc/supervisor/conf.d/assets.conf
  notify:
    - restart supervisor
    - restart nginx

